### ISSUE TITLE
播放器进度条位置好像不太对，打开播放详情页面进度条会跟下面的按钮重合

### ISSUE THREAD

**Issue by Nazrin720** [FlysoftBeta/ReLive#1]
![QQ截图20230213132805](https://user-images.githubusercontent.com/63951577/218378104-0d2b49a4-9ac2-4fdb-bb0f-765bae727163.png)
![QQ截图20230213132857](https://user-images.githubusercontent.com/63951577/218378139-e8382b62-29fe-45b4-89a4-76d7d8d1a76b.png)
![QQ截图20230213132959](https://user-images.githubusercontent.com/63951577/218378271-d2137e60-f6cd-486e-8355-289379844d9d.png)
只订阅了这些插件，重启过网易云但是好像还是不好使，打开播放详情页面进度条会跟下面的按钮重合

**Comment by Nazrin720** [comment]
研究了一些发现设置里面好像可以改，我没看见看见= =

**Comment by FlysoftBeta** [comment]
> 研究了一些发现设置里面好像可以改，我没看见看见= =

能提供一下设置项吗

**Comment by Nazrin720** [comment]
> 所有者



> > 研究了一些发现设置里面好像可以改，我没看见看见= =
> 
> 能提供一下设置项吗

![QQ截图20230215215443](https://user-images.githubusercontent.com/63951577/219046875-eee28b57-c6c2-4e1a-9cbf-3312b0c9397d.png)
把这个选项关掉就可以了

**Comment by FlysoftBeta** [comment]
好的，谢谢
