### ISSUE TITLE
时间轴调节BUG

### ISSUE THREAD

**Issue by misaka10384** [FlysoftBeta/ReLive#3]
![image](https://user-images.githubusercontent.com/61707010/219417552-4e4375d8-c766-41ef-8d37-089227b68f1f.png)
当指针到黑色前面的区域时无法指定时间轴  黑色后面可以  初步怀疑是歌曲名称包括那颗心占用了时间轴区域 建议修复

**Comment by FlysoftBeta** [comment]
> ![image](https://user-images.githubusercontent.com/61707010/219417552-4e4375d8-c766-41ef-8d37-089227b68f1f.png) 当指针到黑色前面的区域时无法指定时间轴 黑色后面可以 初步怀疑是歌曲名称包括那颗心占用了时间轴区域 建议修复

已知问题，目前在寻找解决方案

**Comment by FlysoftBeta** [comment]
> ![image](https://user-images.githubusercontent.com/61707010/219417552-4e4375d8-c766-41ef-8d37-089227b68f1f.png) 当指针到黑色前面的区域时无法指定时间轴 黑色后面可以 初步怀疑是歌曲名称包括那颗心占用了时间轴区域 建议修复

另外能发送一下壁纸吗，我觉得不错，谢谢🤔

**Comment by misaka10384** [comment]
你可以尝试调整一下时间轴的优先级.jpg 图我发你邮箱了

**Comment by FlysoftBeta** [comment]
谢谢啦

**Comment by FlysoftBeta** [comment]
> 你可以尝试调整一下时间轴的优先级.jpg 图我发你邮箱了

这个可能调整不了，歌曲信息和播放条其实是两层div叠在一起，不过问题已经修复了，可以安装这个版本试试
https://github.com/FlysoftBeta/ReLive/releases/download/0.2.8/relive-theme.plugin
