### ISSUE TITLE
一个与Refined Now Playing插件的兼容性问题

### ISSUE THREAD

**Issue by FKcrown** [FlysoftBeta/ReLive#6]
![image](https://user-images.githubusercontent.com/79238509/236668212-03bb16a3-0272-4365-8192-2c625c3dd2c5.png)

## 开启Refined Now Playing设置里的`优化底栏`选项时，进度条会超出屏幕

![image](https://user-images.githubusercontent.com/79238509/236668209-0eddce1c-b839-4153-9a13-0247934cf168.png)

**Comment by FlysoftBeta** [comment]
ReLive主题默认会修改播放页面，和RNP的优化底栏选项**不兼容**，如果需要使用RNP的底栏请在StyleSnippet配置界面**关闭修改播放页面**选项（这会使用RNP自带的播放页面）。

实际上这个选项在启用**修改播放页面**时应该被隐藏掉的，可能是我写的匹配规则失效了。

**Comment by FKcrown** [comment]
已经解决了，关闭`修改播放页面`后还需要打开RNP的`优化底栏`选项才能完整显示进度条

## 未开`优化底栏`
<img width="767" alt="image_111" src="https://github.com/FlysoftBeta/ReLive/assets/79238509/a6a5030c-d619-47ca-b2b1-babb1dd7b5e0">


## 开启`优化底栏`
<img width="767" alt="image_112" src="https://github.com/FlysoftBeta/ReLive/assets/79238509/221ace35-abd8-45ff-8a98-695dc79dfa51">

**Comment by FlysoftBeta** [comment]
> 已经解决了，关闭`修改播放页面`后还需要打开RNP的`优化底栏`选项才能完整显示进度条
> ## 未开`优化底栏`
> <img alt="image_111" width="767" src="https://user-images.githubusercontent.com/79238509/240501639-a6a5030c-d619-47ca-b2b1-babb1dd7b5e0.png">
> ## 开启`优化底栏`
> <img alt="image_112" width="767" src="https://user-images.githubusercontent.com/79238509/240501653-221ace35-abd8-45ff-8a98-695dc79dfa51.png">

感谢报告，这个选项确实需要手动开启
